version: 2.1
orbs:
    slack: circleci/slack@3.4.2
    jq: circleci/jq@2.2.0
jobs:
    test:
        docker:
            - image: rishabhpoddar/supertokens_go_driver_testing
        resource_class: large
        steps:
            - add_ssh_keys:
                  fingerprints:
                      - "b3:da:ef:15:52:aa:a3:69:c3:6b:14:0c:be:23:b7:c7"
            - checkout
            - run: go version
            - run: go get ./...
            - run: (cd .circleci/ && ./doTests.sh)
            - slack/status

workflows:
    version: 2
    tagged-build:
        jobs:
            - test:
                  context:
                      - slack-notification
                  filters:
                      tags:
                          only: /dev-v[0-9]+(\.[0-9]+)*/
                      branches:
                          ignore: /.*/
