db:
  host: 'localhost'
  port: 5432
  user: ''
  password: ''
  dbname: ''
server:
  apiPort: ':3001'
  websitePort: ':3000'
GITHUB_CLIENT_SECRET: '5e8917cdcca5ff901c208e6512fbe6771f12b6dd'
GITHUB_CLIENT_ID : '7e1cf377aa7cbd91cd8c'
